name: Generate Snake

on:
  # Run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *" 
  
  # Allows you to run it manually from the Actions tab for testing
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # GRANT PERMISSION to write to the repository
    permissions: 
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          # Name of your GitHub user
          github_user_name: mrmushii
          
          # The list of files to generate.
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Push to the output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
